apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: databases
type: Opaque
stringData:
  root-password: "rootpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  secret-key: "promeni-ovaj-tajni-kljuc-u-produkciji-mora-biti-dugacak"
  algorithm: "HS256"
  access-token-expire-minutes: "60"
  postmark-api-key: "c10714cd-7fef-413d-bd31-0563188ad4b6"
  postmark-from-email: "md20220234@student.fon.bg.ac.rs"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-password: "grafanaPassword123"
