apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: milicaadrljacaa/event-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
            - name: DB_HOST
              value: "mysql-event.databases.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "event_db"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: app
spec:
  selector:
    app: event-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
