apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: milicaadrljacaa/payment-service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m" # minimalno CPU koje Pod treba
              memory: "128Mi" # minimalno RAM koje Pod treba
            limits:
              cpu: "500m" # maksimalno CPU koje Pod može koristiti
              memory: "512Mi" # maksimalno RAM koje Pod može koristiti
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
            - name: DB_HOST
              value: "mysql-payment.databases.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "payment_db"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: app
spec:
  selector:
    app: payment-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
